format = """\
[ 󰣇 ](bg:#E78284 fg:#161616)\
[](fg:#E78284 bg:#666666)\
$time\
[](fg:#666666 bg:#3D3D3D)\
$directory\
[](fg:#3D3D3D bg:#E5C890)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#E5C890 bg:#161616)\
$character\
"""

# No new line between shell prompts
add_newline = false

# No line-break between shell prompts
[line_break]
disabled = true


[directory]
format = "[  $path ]($style)"
style = "fg:#ffffff bg:#3D3D3D"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#303446 bg:#E5C890"

[git_status]
format = '[$all_status]($style)'
style = "fg:#303446 bg:#E5C890"
ahead = "⇡${count} "
diverged = "⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
modified = "!${count} "
untracked = "?${count} "
staged = "+${count} "

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[ 󱎫 $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ➜](#a6d189) '
error_symbol = '[ ](#E78284) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[ 󱑍 $time ](bg:#666666 fg:#ffffff)]($style)'
