forward_stdio yes

# ──────────────────────────────
# Layout
# ──────────────────────────────

enabled_layouts splits

window_padding_width 4
window_border_width 0.1

active_border_color   #FFC799
inactive_border_color #282828

# ──────────────────────────────
# Focus
# ──────────────────────────────

inactive_text_alpha 1.0
custom_shaders dim-inactive-windows

# ──────────────────────────────
# Scrollback
# ──────────────────────────────
# Enter scroll/copy mode
map ctrl+alt+space show_scrollback
scrollback_pager nvim -u NONE -n --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

# ──────────────────────────────
# Splits
# ──────────────────────────────

map ctrl+alt+v launch --location=vsplit --cwd=current --add-to-session=.
map ctrl+alt+x launch --location=hsplit --cwd=current --add-to-session=.
map ctrl+alt+w close_window


# ──────────────────────────────
# Tabs
# ──────────────────────────────

map alt+t new_tab_with_cwd
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5

map ctrl+alt+r set_tab_title " "


# ──────────────────────────────
# Projects / sessions
# ──────────────────────────────

map ctrl+alt+p launch --type=overlay --add-to-session=! --allow-remote-control ~/.config/kitty/session_picker.sh

map ctrl+alt+o goto_session -1

# Create a session / project
map ctrl+alt+s combine | save_as_session --save-only --base-dir ~/.local/share/kitty/sessions --match=session:. . | kitten notify --urgency=low "Kitty" "Session saved"

# ──────────────────────────────
# Vesper-ish appearance
# ──────────────────────────────
background #101010
foreground #d4d4d4
cursor #343434
cursor_text_color #ffffff
selection_background #232323
selection_foreground #d4d4d4

# Normal
color0  #1C1C1C
color1  #FF8080
color2  #99FFE4
color3  #FFC799
color4  #A0A0A0
color5  #FFCFA8
color6  #99FFE4
color7  #CFCFCF

# Bright
color8  #505050
color9  #FF9A9A
color10 #B8FFF0
color11 #FFCFA8
color12 #D0D0D0
color13 #FFB0B0
color14 #B8FFF0
color15 #FFFFFF

# ──────────────────────────────
# Kitty navigator neovim plugin
# ──────────────────────────────
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l

# Required for neovim navigation plugin
allow_remote_control yes
listen_on unix:@mykitty

# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# ──────────────────────────────
# Tab bar
# ──────────────────────────────
tab_bar_edge bottom
tab_bar_style separator

tab_separator "   "

tab_bar_align left
tab_bar_min_tabs 1

tab_bar_background #101010

active_tab_background #101010
active_tab_foreground #ffc799
active_tab_font_style bold

inactive_tab_background #101010
inactive_tab_foreground #FFFFFF
inactive_tab_font_style normal

tab_title_template "{custom}"

tab_bar_filter session:~
