require("catppuccin").setup()
require("nvim-autopairs").setup()
require("configs.nvim-tree")
require("configs.lualine")
require("configs.tree-sitter")
require("configs.vim-cmp")
require("configs.mason")
require("configs.lsp")
