[font]
size = 14

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"

[general]
import = ["~/.config/alacritty/shared.toml"]
