# Colors (Vesper)
# Source https://github.com/raunofreiberg/vesper

[colors.primary]
background = '#101010'
foreground = '#ffffff'

[colors.normal]
black   = "#101010"
red     = "#f5a191"
green   = "#90b99f"
yellow  = "#e6b99d"
blue    = "#aca1cf"
magenta = "#e29eca"
cyan    = "#ea83a5"
white   = "#A0A0A0"

[colors.bright]
black   = "#7E7E7E"
red     = "#ff8080"
green   = "#99FFE4"
yellow  = "#FFC799"
blue    = "#b9aeda"
magenta = "#ecaad6"
cyan    = "#f591b2"
white   = "#ffffff"

[colors.cursor]
text = "#101010"
cursor = "#ffffff"

[colors.selection]
text = "#ffffff"
background = "#282828"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[scrolling]
history = 10000
multiplier = 3
